M48
; DRILL file {KiCad 9.0.1} date 2025-07-04T11:11:24+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-07-04T11:11:24+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X88.5Y-77.9
X123.2Y-135.57
X211.85Y-135.3
X229.6Y-77.9
M30
